name: CI

on:
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm and cache
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc' # .nvmrc 파일 사용
          cache: 'pnpm'

      - name: Enable Corepack to use pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type check
        run: pnpm type-check

      - name: Run linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run build
        run: pnpm build