name: Debug Sync

on:
  push:
    branches: [main]

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.repository == 'FESI-10th-team6/dallem'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug Repository Info
      run: |
        echo "=== Repository Information ==="
        echo "Current repository: ${{ github.repository }}"
        echo "GitHub actor: ${{ github.actor }}"
        echo "GitHub event name: ${{ github.event_name }}"
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub sha: ${{ github.sha }}"
        
    - name: Debug Secrets
      run: |
        echo "=== Secrets Information ==="
        echo "PERSONAL_REPO_OWNER exists: ${{ secrets.PERSONAL_REPO_OWNER != '' }}"
        echo "PERSONAL_REPO_OWNER value: ${{ secrets.PERSONAL_REPO_OWNER }}"
        echo "PERSONAL_REPO_NAME exists: ${{ secrets.PERSONAL_REPO_NAME != '' }}"
        echo "PERSONAL_REPO_NAME value: ${{ secrets.PERSONAL_REPO_NAME }}"
        echo "PERSONAL_GITHUB_TOKEN exists: ${{ secrets.PERSONAL_GITHUB_TOKEN != '' }}"
        echo "PERSONAL_GITHUB_TOKEN length: ${#PERSONAL_GITHUB_TOKEN}"
        
    - name: Test Git Access
      run: |
        echo "=== Testing Git Access ==="
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 개인 레포에 접근 테스트
        echo "Testing access to personal repository..."
        git ls-remote https://x-access-token:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ secrets.PERSONAL_REPO_OWNER }}/${{ secrets.PERSONAL_REPO_NAME }}.git || echo "Access failed"
        
    - name: Debug Token Permissions
      run: |
        echo "=== Token Permissions Test ==="
        # GitHub API로 토큰 권한 확인
        curl -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/user || echo "Token authentication failed"
             
        curl -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ secrets.PERSONAL_REPO_OWNER }}/${{ secrets.PERSONAL_REPO_NAME }} || echo "Repository access failed"