name: Sync Design Tokens

on:
  pull_request:
    branches: 'designToken'
    paths:
      - 'designToken.json' # design-tokens.json 경로에 맞게 조정
      - '.github/workflows/design-token-build.yml'

jobs:
  generate-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate design token output
        run: pnpm run style:tokens

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add path/to/generated.css  # 실제 생성 파일 경로 지정
          git diff --cached --quiet || git commit -m "chore: update design token output"
          git push
