name: Sync to Personal Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    name: Sync to Personal Repo
    runs-on: ubuntu-latest
    if: github.repository == 'FESI-10th-team6/dallem'

    # 이 작업이 저장소의 콘텐츠를 읽을 수 있도록 명시적으로 권한을 부여
    permissions:
      contents: read

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 시크릿 값이 올바르게 로드되었는지 확인
      - name: Verify secrets
        run: |
          echo "Syncing to: ${{ secrets.PERSONAL_REPO_OWNER }}/${{ secrets.PERSONAL_REPO_NAME }}"
          if [ -z "${{ secrets.PERSONAL_REPO_OWNER }}" ] || [ -z "${{ secrets.PERSONAL_REPO_NAME }}" ]; then
            echo "::error:: PERSONAL_REPO_OWNER or PERSONAL_REPO_NAME secret is not set!"
            exit 1
          fi

      - name: Push to personal repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 저장소 주소를 변수로 만들어 가독성을 높이고 에러를 방지합니다.
          TARGET_REPO="https://x-access-token:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ secrets.PERSONAL_REPO_OWNER }}/${{ secrets.PERSONAL_REPO_NAME }}.git"
          
          git remote add personal_repo "${TARGET_REPO}"
          
          git push personal_repo main:main --force