name: Sync to Personal Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'FESI-10th-team6/dallem'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Sync to personal repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 개인 레포로 push
        git push https://x-access-token:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${{ secrets.PERSONAL_REPO_OWNER }}/${{ secrets.PERSONAL_REPO_NAME }}.git main:main